// Generated by CoffeeScript 1.6.2
(function() {
  var Elemental, namespaces, root;

  root = this;
  Elemental = void 0;
  if (typeof exports !== "undefined") {
    Elemental = exports;
  } else {
    Elemental = root.Elemental = {};
  }
  namespaces = [root];
  Elemental.load = function(element) {
    var container;

    container = $(element);
    return container.find("*").andSelf().filter("[data-behavior]").each(function(index, element) {
      var behaviors, that;

      that = $(element);
      behaviors = that.attr("data-behavior");
      return _.each(behaviors.split(" "), function(behavior) {
        var fn, fns, namespaced;

        namespaced = behavior.split(".");
        fns = _.map(namespaces, function(namespace) {
          return _.reduce(namespaced, (function(prev, next) {
            if (prev !== undefined) {
              return prev[next];
            } else {
              return undefined;
            }
          }), namespace);
        });
        fn = _.find(fns, function(fn) {
          return undefined !== fn;
        });
        if (undefined !== fn) {
          return fn(that);
        }
      });
    });
  };
  return Elemental.addNamespace = function(namespace) {
    return namespaces.push(namespace);
  };
})();
